database:
  host    : ""
  user    : ""
  passport: ""
  port    : 3306
  name    : ""

server:
  port: "8989"

jwt: 
  expires : 48
  issuer  : ""
  secret : ""

email:
  sender: ""
  pwd: ""
  smtpAddr : "smtp.qq.com"
  smtpPort : 25